copyright: Copyright 2016 Philip Delaquess

logging:
    level: INFO
    loggers:
        "pld.gin.server.engine": DEBUG

server:
    rootPath: /api/

assets:
    overrides:
        /: gin-web/src/main/resources/assets

database:
    driverClass: org.h2.Driver
    user: sa
# password
    url: jdbc:h2:./gin-db
    properties:
        charSet: UTF-8
    maxWaitForConnection: 1s
    validationQuery: "/* MyService Health Check */ SELECT 1"
    minSize: 8
    maxSize: 32
    checkConnectionWhileIdle: false
    evictionInterval: 10s
    minIdleTime: 1 minute
