package pld.gin.dto;

/**
 *
 */
public enum PlayerState {
    AWAITING_OPPONENT_ARRIVAL,
    AWAITING_OPPONENT_ACTION,
    PONE_INITIAL_DRAW,
        // ACCEPT_INITIAL -> DISCARD_OR_KNOCK
        // REJECT_INITIAL -> AWAITING_OPPONENT_ACTION, opponent -> DEALER_INITIAL_DISCARD
    DEALER_INITIAL_DRAW,
        // ACCEPT_INITIAL -> DISCARD_OR_KNOCK
        // REJECT_INITIAL -> AWAITING_OPPONENT_ACTION, opponent -> PONE_INITIAL_DECK
    NORMAL_DRAW,
        // DRAW_PACK -> DISCARD_OR_KNOCK
        // DRAW_DISCARD -> DISCARD_OR_KNOCK
    DISCARD_OR_KNOCK,
        // DISCARD -> AWAITING_OPPONENT_ACTION, opponent -> NORMAL_DRAW
        // KNOCK -> (later)
    ACKNOWLEDGE_DEAL
        // ACKNOWLEDGE -> next deal, AWAITING_OPPONENT_ACTION or PONE_INITIAL_DRAW, opponent -> the other state
}
